TRIG = 17
ECHO = 27

#MODE_PIN = 12
#FORWARD_PIN = 16
#RIGHT_PIN = 20
#LEFT_PIN = 21
#PINs = [MODE_PIN, FORWARD_PIN, RIGHT_PIN, LEFT_PIN]

OUT_GPIOs   = [TRIG]
IN_GPIOs    = [ECHO]
#GPIOs       = [OUT_GPIOs, IN_GPIOs]

